repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7  # Use the latest version available
    hooks:
      - id: autopep8
        args: ['--in-place', '--aggressive', '--aggressive']
        files: \.py$
