repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7  # Use the latest version here
    hooks:
      - id: autopep8
        args: ['--in-place', '--aggressive', '--aggressive']  # Use aggressive formatting
        files: \.py$
