name: Bandit Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit hw2_debugging.py > post_traces/bandit_debugging_output.log
          bandit rand.py > post_traces/bandit_rand_output.log
