name: Autopep8 Formatting
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install autopep8
          pip install pytest
          pip install pylint pyright bandit

      - name: Run autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive --recursive -v .

      - name: Test with pytest
        run: pytest my_test.py

      - name: Run Static Analysis 
        run: |
          pylint hw2_debugging.py > post_traces/pylint_debugging_output.log
          pylint rand.py > post_traces/pylint_rand_output.log
          pyright hw2_debugging.py > post_traces/pyright_debugging_output.log
          pyright rand.py > post_traces/pyright_rand_output.log
          bandit hw2_debugging.py > post_traces/bandit_debugging_output.log
          bandit rand.py > post_traces/bandit_rand_output.log